dist: precise
language: node_js
node_js:
  - "4"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - "node --version"
  - "npm --version"
  - "nvm --version"
  - "firefox --version"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - "npm test"
