// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/c867637b9eb295d76f9458cf246bdbe952616adb/webpack-stream/webpack-stream.d.ts
declare module "webpack-stream" {
  import webpack = require("webpack");

  interface WebpackStreamStatic {
    /**
     * Run webpack with the default configuration.
     */
    (): NodeJS.ReadWriteStream;

    /**
     * Run webpack with the specified configuration.
     *
     * @param {config} Webpack configuration
     */
    (config: webpack.Configuration): NodeJS.ReadWriteStream;

    /**
     * Run webpack with the specified configuration and webpack instance
     *
     * @param {config} Webpack configuration
     * @param {webpack} A webpack object
     */
    (config: webpack.Configuration, webpack: webpack.Webpack): NodeJS.ReadWriteStream;

    /**
     * Run webpack with the specified configuration and webpack instance
     *
     * @param {config} Webpack configuration
     * @param {webpack} A webpack object
     * @param {callback} A callback with the webpack stats and error objects.
     */
    (config: webpack.Configuration,
     webpack: webpack.Webpack,
     callback?: (err: Error, stats: webpack.compiler.Stats) => void): NodeJS.ReadWriteStream;
  }

  var webpackStream: WebpackStreamStatic;

  export = webpackStream;
}
