// Generated by CoffeeScript 1.6.2
(function() {
  BrowserFS.ApiError = (function() {
    ApiError.NETWORK_ERROR = 0;

    ApiError.INVALID_PARAM = 400;

    ApiError.INVALID_TOKEN = 401;

    ApiError.AUTH_ERROR = 403;

    ApiError.NOT_FOUND = 404;

    ApiError.DRIVE_FULL = 507;

    ApiError.NOT_SUPPORTED = 405;

    ApiError.PERMISSIONS_ERROR = 900;

    function ApiError(type, message) {
      this.type = type;
      this.message = message != null ? message : "";
    }

    ApiError.prototype.toString = function() {
      var typeStr;

      typeStr = (function() {
        switch (this.type) {
          case BrowserFS.ApiError.NETWORK_ERROR:
            return 'Network Error';
          case BrowserFS.ApiError.INVALID_PARAM:
            return 'Invalid Param';
          case BrowserFS.ApiError.INVALID_TOKEN:
            return 'Invalid Token';
          case BrowserFS.ApiError.AUTH_ERROR:
            return 'Auth Error';
          case BrowserFS.ApiError.NOT_FOUND:
            return 'Not Found';
          case BrowserFS.ApiError.DRIVE_FULL:
            return 'Drive Full';
          case BrowserFS.ApiError.NOT_SUPPORTED:
            return 'Not Supported';
          case BrowserFS.ApiError.PERMISSIONS_ERROR:
            return 'Permissions Error';
          default:
            return 'Error';
        }
      }).call(this);
      return "BrowserFS " + typeStr + ": " + this.message;
    };

    return ApiError;

  })();

}).call(this);
