// Generated by CoffeeScript 1.6.2
(function() {
  var startTime;

  startTime = Date.now();

  BrowserFS.node.process = (function() {
    function process() {}

    process._cwd = '/';

    process.chdir = function(dir) {
      return this._cwd = BrowserFS.node.path.resolve(dir);
    };

    process.cwd = function() {
      return this._cwd;
    };

    process.platform = function() {
      return 'browser';
    };

    process.uptime = function() {
      return ((Date.now() - startTime) / 1000) | 0;
    };

    return process;

  })();

}).call(this);
