// Generated by CoffeeScript 1.6.2
(function() {
  BrowserFS.node.fs.Stats = (function() {
    Stats.FILE = 1;

    Stats.DIRECTORY = 2;

    Stats.SYMLINK = 3;

    Stats.SOCKET = 4;

    function Stats(item_type, size, mode, atime, mtime, ctime) {
      this.item_type = item_type;
      this.size = size;
      this.mode = mode != null ? mode : 0x1a4;
      this.atime = atime != null ? atime : new Date();
      this.mtime = mtime != null ? mtime : new Date();
      this.ctime = ctime != null ? ctime : new Date();
      this.blocks = Math.ceil(size / 512);
      this.dev = 0;
      this.ino = 0;
      this.rdev = 0;
      this.nlink = 1;
      this.blksize = 4096;
      this.uid = 0;
      this.gid = 0;
    }

    Stats.prototype.clone = function() {
      return new BrowserFS.node.fs.Stats(this.item_type, this.size, this.mode, this.atime, this.mtime, this.ctime);
    };

    Stats.prototype.isFile = function() {
      return this.item_type === Stats.FILE;
    };

    Stats.prototype.isDirectory = function() {
      return this.item_type === Stats.DIRECTORY;
    };

    Stats.prototype.isSymbolicLink = function() {
      return this.item_type === Stats.SYMLINK;
    };

    Stats.prototype.isSocket = function() {
      return this.item_type === Stats.SOCKET;
    };

    Stats.prototype.isBlockDevice = function() {
      return true;
    };

    Stats.prototype.isCharacterDevice = function() {
      return false;
    };

    Stats.prototype.isFIFO = function() {
      return false;
    };

    return Stats;

  })();

}).call(this);
