// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/merge2/merge2.d.ts
declare module 'merge2' {
    interface IOptions {
        end?: boolean;
        objectMode?: boolean;
    }

    interface IMerge2Stream extends NodeJS.ReadWriteStream {
        add(...args: Array<NodeJS.ReadWriteStream | IMerge2Stream | Array<NodeJS.ReadWriteStream | IMerge2Stream | IOptions>>): IMerge2Stream;
    }

    interface IMerge2 {
        (...args: Array<NodeJS.ReadWriteStream | IMerge2Stream | Array<NodeJS.ReadWriteStream | IMerge2Stream> | IOptions>): IMerge2Stream;
    }

    var _tmp: IMerge2;
    export = _tmp;
}
