// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/40c950b9239ddfc16a3e4b45add90bc9b06f3647/gulp-rename/gulp-rename.d.ts
declare module "gulp-rename" {
    interface ParsedPath {
        dirname?: string;
        basename?: string;
        extname?: string;
    }

    interface Options extends ParsedPath {
        prefix?: string;
        suffix?: string;
    }

    function rename(name: string): NodeJS.ReadWriteStream;
    function rename(callback: (path: ParsedPath) => any): NodeJS.ReadWriteStream;
    function rename(opts: Options): NodeJS.ReadWriteStream;

    /**
     * This is required as per:
     * https://github.com/Microsoft/TypeScript/issues/5073
     */
    namespace rename {}

    export = rename;
}
